import Head from 'next/head'
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/pagination";

import { Mousewheel, Pagination } from "swiper";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Swiper
            direction={"vertical"}
            slidesPerView={1}
            spaceBetween={30}
            mousewheel={true}
            pagination={{
                clickable: true,
            }}
            modules={[Mousewheel, Pagination]}
            className="mySwiper"
        >
            <SwiperSlide> <div className="text-black">Home</div></SwiperSlide>
            <SwiperSlide> <div className="text-black">Random</div></SwiperSlide>
            <SwiperSlide> <div className="text-black">Random</div></SwiperSlide>
            <SwiperSlide> <div className="text-black">Random</div></SwiperSlide>
            <SwiperSlide> <div className="text-black">Random</div></SwiperSlide>
            <SwiperSlide> <div className="text-black">Random</div></SwiperSlide>
            <SwiperSlide> <div className="text-black">Random</div></SwiperSlide>
            <SwiperSlide> <div className="text-black">Random</div></SwiperSlide>
            <SwiperSlide> <div className="text-black">Random</div></SwiperSlide>
        </Swiper>
    </>
  )
}
